steps:
- name: 'gcr.io/cloud-builders/yarn:node-14.17.1'
  entrypoint: 'yarn'
  args: ["install","--ignore-engines"]
- name: 'gcr.io/cloud-builders/yarn:node-14.17.1'
  entrypoint: 'yarn'
  args: ["add","@material-ui/icons"]
- name: 'gcr.io/cloud-builders/yarn:node-14.17.1'
  entrypoint: 'yarn'
  args: ["add","@material-ui/core"]
- name: 'gcr.io/cloud-builders/yarn:node-14.17.1'
  entrypoint: 'yarn'
  args: ["install"]
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'npm'
  args: ["run","build"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'